name: "airdump-device-tracker"
description: "Airodump-ng device tracker addon"
version: "0.0.3"
slug: "aircrack-ng"
init: false
host_network: true
full_access: true
devices:
    - /dev/rfkill
#   - /dev/null
#   - /dev/wlan0
#   - /dev/wlan1
#   - /dev/
privileged: 
  - NET_RAW
  - NET_ADMIN
  - SYS_RAWIO
  - SYS_MODULE
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  
options:
  WIFI_DEV : wlp2s0
  WIFI_BAND2_4 : true
  WIFI_BAND5 : true
  WIFI_2_4_SSID:
    test1
    test2
    test3
  WIFI_5_SSID:
    test5g
    test5_1g